import Head from 'next/head'
import { useState , useEffect } from "react";
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export default function Offline() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Offline Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.header}>
         <h1>Offline</h1>
      </div>
                                                                        

    </div>
  )
}
