import Head from 'next/head'
import { useState , useEffect } from "react";
import Image from 'next/image'
import styles from '../styles/Auth.module.scss'
import Authform from '../comps/Authform'

export default function Auth() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Auth Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

   

      <div className="main">
        <div className="left_area">
          <lottie-player src="https://assets10.lottiefiles.com/packages/lf20_cdvdgap1.json"  background="transparent" height="100px" speed="1"   loop  autoplay />

        </div>

        <div className="right_area">
<Authform />
        </div>

      </div>
    
    </div>
  )
}
