import Head from 'next/head'
import { useState , useEffect } from "react";
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import Leftarea from '../comps/Leftarea';


export default function Home() {
  const router = useRouter()

  useEffect(() => {
    if (localStorage.getItem("authcheck") == null) {
      router.push('Auth');
    }
    else{
      console.log("Alrealy Authenicated")
    }

    if (localStorage.getItem("reload") == "true") {
      window.location.reload()
      localStorage.setItem("reload" , "false")

    }
  
  }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>Chitchatz</title>
        <meta name="description" content="Generated by Chitchatz" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <Leftarea />

     
    </div>
  )
}
